### PR TITLE
Fix cowboy.start

### PR DESCRIPTION
**Pull request by lun-4**

### CODE REVIEW

**Comment by lpil** [comment]
Hi @lun-4, could you explain the change and the reason for it? Thank you

**Comment by michallepicki** [comment]
Maybe I'm unnecessarily chiming in but I am guessing @lun-4 saw the [supervisors](https://gleam.run/news/gleam-v0.12-and-gleam-otp-v0.1-released/#supervisors) section of the gleam 0.12 announcement and assumed `web.start` is analogous to `cowboy.start`

**Comment by lun-4** [comment]
@lpil I was attempting to use `gleam_cowboy` on gleam 0.12.0 but `start` returning `Result(Pid, Dynamic)` caused a compile error. Noticed `ErlangStartResult` exists on `gleam_otp`, so I used it and bumped dependency versions to account for that on CI.

**Comment by lpil** [comment]
Ah I see! There is still a problem here in that `ErlangStartResult` isn't correct, it really should be `Result(Pid, Dynamic)` and Gleam libraries should return a normal `StartResult`. Sorry about this problem here, I've not yet updated the other libraries to use `gleam_otp` v0.1.

I'm going to publish a new version of `gleam_otp` now, would you like to update this library or shall I?

**Comment by lun-4** [comment]
I can do it!

**Comment by lpil** [comment]
Thank you!

This function may be useful? https://hexdocs.pm/gleam_otp/gleam/otp/supervisor/#wrap_erlang_start_function Depends exactly how its done

**Review by lpil — APPROVED** [review]
Very nice! Thank you!

**Pull request merged**
